### ISSUE TITLE
Osakkeet

### ISSUE THREAD

**Issue by vnuotio** [VeriHeppi/Monopeli#5]
Osakkeet jotai voi ostaa ja joilla peritään rahaa. Käytännössä kuva laudalla ja vaikka UI:n alakulmassa ja sit vielä et niil on arvo ja nii edes päin.

**Comment by MikkoYlihonkaluoma** [comment]
eiks niitä kutsuta osakkeiks niitä paikkoja mitä ostetaan?!?!
